name: 'PR Changelog'
description: 'Update PR changelog'
inputs:
  token:
    description: 'github token'
    required: true
  type:
    description: 'bot type: release or onprem'
    required: true
  base:
    description: 'base branch used when not triggered in pull_request context'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/changelogAction/index.js'
