name: 'PR Changelog'
description: 'Update PR changelog'
inputs:
  token:
    description: 'github token'
    required: true
  type:
    description: 'bot type: release or onprem'
    required: true
runs:
  using: 'node12'
  main: 'index.js'