name: Changelog

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: release
          base: master
