name: Create Release

on:
  push:
    branches:
      - 'develop'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './createReleaseAction'
        with:
          token: ${{ secrets.GH_TOKEN }}
          head: develop
          base: master
          title: Next Release
          reviewers: 'limtingzhi'
