name: Deploy Staging

on:
  push:
    branches:
      - alpha
      - develop
  workflow_run:
    workflows:
      - "dependabot-check"
    branches: [dependabot/**]
    types:
      - completed

jobs:
  deploy:
    uses: ./.github/workflows/deploy-client.yml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
